services:
  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - database_volume:/var/lib/mysql
      - ./scripts/mysql/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./scripts/mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  database_volume:
